# Form implementation generated from reading ui file 'app/ui/search_form.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form.resize(397, 301)
        self.formLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 391, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.firstNameLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.firstNameLabel)
        self.firstNameLineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.firstNameLineEdit.setObjectName("firstNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.firstNameLineEdit)
        self.lastNameLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lastNameLabel)
        self.lastNameLineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lastNameLineEdit.setObjectName("lastNameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lastNameLineEdit)
        self.sentStatusLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.sentStatusLabel.setObjectName("sentStatusLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.sentStatusLabel)
        self.sentStatusComboBox = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.sentStatusComboBox.setObjectName("sentStatusComboBox")
        self.sentStatusComboBox.addItem("")
        self.sentStatusComboBox.addItem("")
        self.sentStatusComboBox.addItem("")
        self.sentStatusComboBox.addItem("")
        self.sentStatusComboBox.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sentStatusComboBox)
        self.btnSubmit = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.btnSubmit.setObjectName("btnSubmit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btnSubmit)
        self.completedStatusLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.completedStatusLabel.setObjectName("completedStatusLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.completedStatusLabel)
        self.completedStatusComboBox = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.completedStatusComboBox.setObjectName("completedStatusComboBox")
        self.completedStatusComboBox.addItem("")
        self.completedStatusComboBox.addItem("")
        self.completedStatusComboBox.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.completedStatusComboBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Search participants"))
        self.firstNameLabel.setText(_translate("Form", "firstName"))
        self.lastNameLabel.setText(_translate("Form", "lastName"))
        self.sentStatusLabel.setText(_translate("Form", "Invitation email"))
        self.sentStatusComboBox.setItemText(0, _translate("Form", "-"))
        self.sentStatusComboBox.setItemText(1, _translate("Form", "Sent invitations only"))
        self.sentStatusComboBox.setItemText(2, _translate("Form", "Unsent invitations"))
        self.sentStatusComboBox.setItemText(3, _translate("Form", "On or before..."))
        self.sentStatusComboBox.setItemText(4, _translate("Form", "On or after..."))
        self.btnSubmit.setText(_translate("Form", "Search"))
        self.completedStatusLabel.setText(_translate("Form", "Response status"))
        self.completedStatusComboBox.setItemText(0, _translate("Form", "-"))
        self.completedStatusComboBox.setItemText(1, _translate("Form", "Completed only"))
        self.completedStatusComboBox.setItemText(2, _translate("Form", "Incompleted only"))
